### ISSUE TITLE
Bluetooth 4.0 only

### ISSUE THREAD

**Issue by bassrock** [MattCBowman/ReactiveCoreBluetooth#1]
Probably good to note that this only works only for bluetooth 4.0

**Comment by MattCBowman** [comment]
Good point - it's definitely not obvious in Apple's site that CoreBluetooth is only 4.0 LE devices. I'll update the docs.

:cactus:

**Comment by bassrock** [comment]
I'll try looking at starting a fork and pull request to add regular bluetooth as well.

**Comment by MattCBowman** [comment]
That would be awesome - I was considering working on that in my spare time as well. I think External Accessory Framework is the way to go for that stuff. :tada:
